name: Build and deploy Jekyll site

on:
  push:
    branches:
      - main  # замените на вашу основную ветку, если другая

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build the site with Jekyll
      uses: actions/jekyll-build-pages@v1
      with:
        source: './'          # Путь к исходным файлам сайта, './' — корень репозитория
        destination: './_site' # Папка для собранного сайта
